[package]
name = "skip_list"
version = "0.1.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
rocksdb = "0.13"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
typename = "0.1.1"
# local dependencies
storage = { path = "../" }