# Work in progress, duplicit commands will be added to a new docker image dedicated to CI builds
kind: pipeline
name: default

steps:
- name: build
  image: adonagy/tezedge-ci-builder:latest
  user: root
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands:
    - cargo clean && cargo build --release

- name: node-run
  image: adonagy/tezedge-ci-builder:latest
  user: root
  detach: true
  environment:
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands: 
    - mkdir /tmp/tezedge
    - cargo run --release --bin light-node -- --config-file ./light_node/etc/tezedge/tezedge.config --log-file /tmp/logs/tezdge.log --protocol-runner "./target/release/protocol-runner" --identity-file /tmp/identity/identity.json


- name: test
  image: adonagy/tezedge-ci-builder:latest
  user: root
  commands:
    - sleep 30
    - cargo test --release test_heads

# - name: tests
#   image: rust:latest
#   user: root
#   commands:
#     - cargo test
