# Work in progress, duplicit commands will be added to a new docker image dedicated to CI builds
kind: pipeline
name: default

steps:
- name: build-tezedge
  image: adonagy/tezedge-ci-builder:latest
  user: root
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands:
    - pwd
    - cargo clean && cargo build --release

# build a container to be used in the next steps
# - name: build-tezedge-image
#   image: plugins/docker
#   settings:
#     username:
#       from_secret: dockerhub_username
#     password:
#       from_secret: dockerhub_token
#     repo: adonagy/tezedge
#     dockerfile: /drone/src/docker/run/Dockerfile
#     tags: latest

# - name: tezedge-node-run
#   image: adonagy/tezedge:latest
#   detach: true

- name: tezedge-node-run
  image: adonagy/tezedge-ci-builder:latest
  user: root
  detach: true
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands: 
    - mkdir /tmp/tezedge
    - cargo run --release --bin light-node -- --config-file ./light_node/etc/tezedge/tezedge.config --protocol-runner "./target/release/protocol-runner" --p2p-port 19733 --identity-file /drone/src/docker/identities/identity_tezedge.json --ffi-calls-gc-treshold=2000

- name: ocaml-node-run
  image: tezos/tezos:babylonnet
  detach: true
  commands:
    - mkdir /home/tezos/data
    - cp /drone/src/docker/identities/identity_ocaml.json /home/tezos/data/identity.json
    - tezos-node run --rpc-addr 0.0.0.0 --net-addr 0.0.0.0:9734 --data-dir /home/tezos/data

- name: bootstrapping
  image: adonagy/tezos-node-bootstrap:latest


- name: test
  image: adonagy/tezedge-ci-builder:latest
  pull: if-not-exists
  user: root
  commands:
    - sleep 5
    - cargo test --release test_heads

