kind: pipeline
name: default

steps:
- name: build
  image: rust:latest
  environment:
    PATH: /home/appuser/.cargo/bin:$PATH
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
  commands:
    - cargo build --release
