kind: pipeline
name: default

steps:
- name: build
  image: simplestakingcom/tezos-opam-builder:debian10
  user: root
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
  commands:
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2019-11-25 -y
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo clean && cargo build --release
    - mkdir /tmp/tezedge

- name: run
  image: simplestakingcom/tezos-opam-builder:debian10
  user: root
  environment:
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands:
    - cargo run --release --bin light-node -- \
                            --config-file "./light_node/etc/tezedge/tezedge.config" \
                            --tezos-data-dir "/tmp/tezedge/tezos-data" \
                            --identity-file "/tmp/tezedge/identity.json" \
                            --bootstrap-db-path "/tmp/tezedge/tezedge-data/" \
                            --network "babylonnet" \
                            --ocaml-log-enabled "true" \
                            --protocol-runner "./target/release/protocol-runner"
