kind: pipeline
name: default

steps:
- name: build
  image: simplestakingcom/tezos-opam-builder:debian10
  environment:
    PATH: /home/appuser/.cargo/bin:$PATH
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
  commands:
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2019-11-25 -y
    - cd /home/appuser && git clone https://github.com/simplestaking/tezedge.git && cd tezedge && cargo build --release
    - mkdir /tmp/tezedge
    - chown appuser:appuser /tmp/tezedge
