kind: pipeline
name: default

steps:
- name: build-tezedge
  image: adonagy/tezedge-ci-builder:latest
  user: root
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands:
    - cargo clean && cargo build --release

- name: tezedge-node-run
  image: adonagy/tezedge-ci-builder:latest
  user: root
  detach: true
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands: 
    - mkdir /tmp/tezedge_developer
    - cargo run --release --bin light-node -- --config-file ./light_node/etc/tezedge/tezedge.config --protocol-runner "./target/release/protocol-runner" --p2p-port 39733 --websocket-address 0.0.0.0:34927 --rpc-port 18732 --tezos-data-dir=/tmp/tezedge_developer

- name: ocaml-node-run
  image: tezos/tezos:babylonnet
  detach: true
  volumes:
    - name: ocaml-node-data
      path: /home/tezos/
  commands:
    - mkdir /home/tezos/data
    - cp /drone/src/docker/identities/identity_ocaml.json /home/tezos/data/identity.json
    - cp -R .tezos-node/context /home/tezos/data/
    - cp -R .tezos-node/store /home/tezos/data/
    - tezos-node run --rpc-addr 0.0.0.0 --net-addr 0.0.0.0:9734 --data-dir /home/tezos/data --history-mode archive 

- name: bootstrapping
  image: adonagy/tezos-node-bootstrap:latest

- name: test
  image: adonagy/tezedge-ci-builder:latest
  pull: if-not-exists
  user: root
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands:
    - cargo test --verbose --release -- --nocapture --ignored integration_test_dev

volumes:
  - name: ocaml-node-data
    host:
      path: /home/ado/tezos-node-backup

trigger:
  branch:
    - master
