kind: pipeline
name: default

steps:
# - name: build-tezedge
#   image: adonagy/tezedge-ci-builder:latest
#   user: root
#   environment:
#     RUST_BACKTRACE: 1
#     SODIUM_USE_PKG_CONFIG: 1
#     OCAML_BUILD_CHAIN: remote
#     LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
#   commands:
#     - cargo clean && cargo build --release

- name: tezedge-node-run
  image: adonagy/tezedge-ci-builder:latest
  user: root
  detach: true
  volumes:
    - name: tezedge-node-data
      path: /tmp/tezedge_developer
  environment:
    RUST_BACKTRACE: 1
    SODIUM_USE_PKG_CONFIG: 1
    OCAML_BUILD_CHAIN: remote
    LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
  commands: 
    - cargo build --release
    - cargo run --release --bin light-node -- --config-file ./light_node/etc/tezedge/tezedge.config --protocol-runner "./target/release/protocol-runner" --p2p-port 39733 --websocket-address 0.0.0.0:34927 --rpc-port 18732 --tezos-data-dir=/tmp/tezedge_developer/tezos-node --bootstrap-db-path=/tmp/tezedge_developer/light-node

- name: ocaml-node-run
  user: root
  image: tezos/tezos:babylonnet
  detach: true
  volumes:
    - name: ocaml-node-data
      path: /home/tezos/data
  commands:
    - cp /drone/src/docker/identities/identity_ocaml.json /home/tezos/data/identity.json
    - tezos-node run --rpc-addr 0.0.0.0 --net-addr 0.0.0.0:9734 --data-dir /home/tezos/data --history-mode archive 

- name: bootstrapping
  image: adonagy/tezos-node-bootstrap:latest

- name: tz-indexer
  image: blockwatch/tzindex:latest
  user: root
  # detach: true
  volumes:
    - name: indexer-data
      path: /data
  environment:
    TZ_RPC_HOST: tezedge-node-run
    TZ_RPC_PORT: 18732
    TZ_SERVER_ADDR: 0.0.0.0
    TZ_SERVER_PORT: 8002
    TZ_SERVER_CORS_ENABLE: true
    TZ_DATABASE_PATH: /data/index
    TZ_SNAPSHOT_PATH: /data/snapshots
    TZ_LOGGING_RPC: debug

# - name: test
#   image: adonagy/tezedge-ci-builder:latest
#   pull: if-not-exists
#   user: root
#   environment:
#     RUST_BACKTRACE: 1
#     SODIUM_USE_PKG_CONFIG: 1
#     OCAML_BUILD_CHAIN: remote
#     LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
#   commands:
#     - cargo test --verbose --release -- --nocapture --ignored integration_test_dev

volumes:
  - name: ocaml-node-data
    host:
      path: /home/ado/tezos-node-backup
  - name: tezedge-node-data
    host:
      path: /home/ado/tezedge-node-backup
  - name: indexer-data
    host:
      path: /home/ado/indexer/data

trigger:
  branch:
    - master

# -------------------

# kind: pipeline
# name: indexer

# steps:
# - name: tezedge-node-run
#   image: adonagy/tezedge-ci-builder:latest
#   user: root
#   detach: true
#   volumes:
#     - name: tezedge-node-data
#       path: /tmp/tezedge_developer
#   environment:
#     RUST_BACKTRACE: 1
#     SODIUM_USE_PKG_CONFIG: 1
#     OCAML_BUILD_CHAIN: remote
#     LD_LIBRARY_PATH: ./tezos/interop/lib_tezos/artifacts
#   commands: 
#     - cargo build --release
#     - cargo run --release --bin light-node -- --config-file ./light_node/etc/tezedge/tezedge.config --protocol-runner "./target/release/protocol-runner" --p2p-port 39733 --websocket-address 0.0.0.0:34927 --rpc-port 18732 --tezos-data-dir=/tmp/tezedge_developer/tezos-node --bootstrap-db-path=/tmp/tezedge_developer/light-node

# - name: tz-indexer
#   image: blockwatch/tzindex:latest
#   user: root
#   # detach: true
#   volumes:
#     - name: indexer-data
#       path: /data
#   environment:
#     TZ_RPC_HOST: tezedge-node-run
#     TZ_RPC_PORT: 18732
#     TZ_SERVER_ADDR: 0.0.0.0
#     TZ_SERVER_PORT: 8002
#     TZ_SERVER_CORS_ENABLE: true
#     TZ_DATABASE_PATH: /data/index
#     TZ_SNAPSHOT_PATH: /data/snapshots

# volumes:
#   - name: ocaml-node-data
#     host:
#       path: /home/ado/tezos-node-backup
#   - name: tezedge-node-data
#     host:
#       path: /home/ado/tezedge-node-backup
#   - name: indexer-data
#     host:
#       path: /home/ado/indexer/data

# trigger:
#   branch:
#     - drone-update